# Generated by Django 2.2.2 on 2019-07-25 20:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('viewer_core', '0002_auto_20190725_2045'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='branch',
            field=models.ManyToManyField(to='viewer_core.Branch'),
        ),
        migrations.AlterField(
            model_name='instractor',
            name='project',
            field=models.ManyToManyField(to='viewer_core.Project'),
        ),
        migrations.AlterField(
            model_name='project',
            name='parent',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='viewer_core.Project'),
        ),
        migrations.AlterField(
            model_name='student',
            name='project',
            field=models.ManyToManyField(to='viewer_core.Project'),
        ),
        migrations.AlterField(
            model_name='tag',
            name='project',
            field=models.ManyToManyField(to='viewer_core.Project'),
        ),
    ]
