# Generated by Django 2.2.2 on 2019-07-30 03:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('viewer_core', '0007_auto_20190730_0218'),
    ]

    operations = [
        migrations.RenameField(
            model_name='instractor',
            old_name='e_mait',
            new_name='e_mail',
        ),
        migrations.RenameField(
            model_name='student',
            old_name='e_mait',
            new_name='e_mail',
        ),
        migrations.RemoveField(
            model_name='student',
            name='branch',
        ),
        migrations.AddField(
            model_name='student',
            name='group',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='viewer_core.Group'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='project',
            name='parent',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='viewer_core.Project'),
        ),
        migrations.AlterField(
            model_name='project',
            name='students',
            field=models.ManyToManyField(to='viewer_core.Student'),
        ),
        migrations.AlterField(
            model_name='project',
            name='tags',
            field=models.ManyToManyField(to='viewer_core.Tag'),
        ),
    ]
