# Generated by Django 2.2.2 on 2019-08-04 14:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('viewer_core', '0011_auto_20190730_0316'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='markdown',
            field=models.TextField(null=True),
        ),
        migrations.AlterField(
            model_name='project',
            name='parent',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='viewer_core.Project'),
        ),
        migrations.AlterField(
            model_name='project',
            name='students',
            field=models.ManyToManyField(to='viewer_core.Student'),
        ),
        migrations.AlterField(
            model_name='project',
            name='tags',
            field=models.ManyToManyField(blank=True, to='viewer_core.Tag'),
        ),
    ]
